version: "3"
services:
  reverseproxy:
    image: yibrahim/reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-user:
    image: yibrahim/udacity-restapi-user
    environment:
      POSTGRESS_USERNAME: $AWS_USERNAME
      POSTGRESS_PASSWORD: $AWS_PASSWORD
      POSTGRESS_DB: $AWS_DATABASE
      POSTGRESS_HOST: $AWS_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $AWS_JWT
      URL: "http://localhost:8100"
  backend-feed:
    image: yibrahim/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: $AWS_USERNAME
      POSTGRESS_PASSWORD: $AWS_PASSWORD
      POSTGRESS_DB: $AWS_DATABASE
      POSTGRESS_HOST: $AWS_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $AWS_JWT
      URL: "http://localhost:8100"
  frontend:
    image: yibrahim/udacity-frontend
    ports:
      - "8100:80"
